### ISSUE TITLE
GUI  icons not loading - showing alternative text instead

### ISSUE THREAD

**Issue by karstenv** [mapcentia/vidi#201]
I have been testing gc2/vidi on an Ubuntu 16 machine under Docker version 19.03.12, build 48a66213fe. I have cloned the code from the GitHub repro on august 6th .  It appears that i have an issue with icons not loading  see [http://www.terragis.net/docs/other/mech.png] http://www.terragis.net/docs/other/mech.png
Seems that the alternative text is shown instead.  I have checked with the developer panel and it seems that there is a couple or 403 errors occurring see [http://www.terragis.net/docs/other/gc2_forbidden.png] http://www.terragis.net/docs/other/gc2_forbidden.png

**Comment by karstenv** [comment]
I have checked again and the problem above I found with Firefox 77.0.1 (64-bit), however it is working cocrrectly in Google Chrome.

**Comment by mapcentia** [comment]
@karstenv Using Browserstack for testing on Windows, Firefox 77 I get this, which seems alright. Which OS are you using?
![image](https://user-images.githubusercontent.com/3850918/98347151-522dc500-2017-11eb-8346-0d133a7d376a.png)

**Comment by mapcentia** [comment]
@karstenv Looking at your screenshot of dev tools I see a problem on the responses with 403 codes. The GC2_HOST place holder in `vidi/config/config.js` is not been filled. You've to manual change that to `http://localhost:8080` or what ever host GC2 has. After you have to restart the Vidi container.

**Comment by karstenv** [comment]
its on windows 7
 
and looks like this

 

  _____

**Comment by mapcentia** [comment]
Just tried on Win7, FF77 without problems. It seems that the CSS is not loaded. Holding it together with its working in Chrome I guess its something with your FF. Do you have any add-blockers activated? Or any plugins, which could block loading of assets?

**Comment by karstenv** [comment]
I could not find anything so far but I m expecting that you are right and
that the trouble has 
to do with the FF installation or setup. I will test with another machine on
FF and report back.

  _____
