### ISSUE TITLE
LayerTree? - layer order in group is reversed?

### ISSUE THREAD

**Issue by giovanniborella** [mapcentia/vidi#290]
Some time during the last couple of weeks, we have observed that the layers inside the layergroups have been reversed. I have been unable to discern where exactly the error originates, but found the point in code where an unsorted list of layers is returned, and reversed the list there.

Added `notSortedLayersAndSubgroupsForCurrentGroup.reverse();` before return statement.

https://github.com/mapcentia/vidi/blob/eca81f7eb6029c7750eae3aefef98dfa08055b75/browser/modules/layerTree/LayerSorting.js#L56-L59

**Comment by mapcentia** [comment]
I believe it's the 2024.6.1 release with the reuse of the cloned meta object (for optimizing the layertree). The reason for cloning is to avoid side effects, but the reuse, even just for single a single callstack, may have this effect. I'll have to look into it.

**Comment by mapcentia** [comment]
Should be fixed in https://github.com/mapcentia/vidi/commit/47251512742eb98cfa09736f9af9eb86e6de89ae
