### ISSUE TITLE
using new textarea widget in editor fails on submit

### ISSUE THREAD

**Issue by giovanniborella** [mapcentia/vidi#301]
when using the textarea with newlines, the feature fails.

![billede](https://github.com/user-attachments/assets/7cce2c09-e4a9-4d4c-8889-7f25c32bc39f)

results in following response in gc2 feature api (i think):

```javascript
{
    "success": false,
    "message": {
        "success": false,
        "message": "Could not decode GeoJSON",
        "code": 500,
        "_execution_time": 0.048
    }
}
``` 

the json-object sent looks like 
```javascript
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"boolean":false,"timestamp":"2024-10-28T11%3A06","timestampz":"2024-10-28T11%3A06%2B01%3A00","text":"this%20is%0Asome%0Anew%0Alines"},"geometry":{"type":"Point","coordinates":[8.71627807617188,56.37361649220435]}}]}
``` 

im guessing that the featureapi decodes the string, but messes up when storing the newlines into the database

**Comment by mapcentia** [comment]
This should work in latest GC2 and Vidi
