### ISSUE TITLE
Error in package.json

### ISSUE THREAD

**Issue by brunnernikolaj** [mapcentia/vidi#57]
When trying to run the project with the grunt hogan browserify command after first cloning and npm installing. you'll get errors that dependencies are missing eg. redux-thunk.

These errors can be fixed by adding the dependencies to package.json

**Comment by mapcentia** [comment]
@brunnernikolaj @baffioso I think the "Npm way" is to init Npm in whatever extension that requires the Npm module. Like the KeplerGL extension: https://github.com/mapcentia/keplergl/tree/master/browser
