### ISSUE TITLE
Error in how the data-gc2-id is read from DOM element

### ISSUE THREAD

**Issue by brunnernikolaj** [mapcentia/vidi#73]
# Issue
On line 188 the jquery function ```data() ``` is used to extract the data attribute from the element.
for some reason each time the function is called it returns the same data, even though the attribute has changed on the element.

stackoverflow question about it:
https://stackoverflow.com/a/28176641

https://github.com/mapcentia/vidi/blob/ca6664ab04b388c38a07243af66f9e8f659b9fc1/browser/modules/bindEvent.js#L174-L193

# Fix

instead of using the ```data()``` function, I would suggest using the ```attr()``` function instead.
I have tested that it works in place of the other function. 
the only other change is that the parameter passed to the function will become 'data-gc2-id' instead of 'gc2-id'

**Comment by mapcentia** [comment]
@brunnernikolaj Fixed in: https://github.com/mapcentia/vidi/commit/9c974bdbf1fe89d067a590837fb26e5185bb71d0
But where is this a problem? In React components?

**Comment by brunnernikolaj** [comment]
Yes exactly. 
here is an example of it in action from the new vidisearch component
https://github.com/frederiksberg/vidisearch/blob/476e6cc9af7573f10ed378dbbc9e5aaf8b532afa/browser/meta/index.js#L153-L168
